services:
  OrthoHelperAPI:
    image: ortho-helper-api:v0.0.test
    ports:
      - 8088:8080    
    volumes:
      - orthohelper-data:/app/data  # Volume pour SQLite
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTIONSTRINGS__DEFAULTCONNECTION=Data Source=/app/data/api.db;
volumes:
  orthohelper-data: